"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar2 from "@/components/nav";
import LoadingScreen from "@/components/LoadingScreen";
import { LoadingProvider, useLoading } from "@/contexts/LoadingContext";
import { useEffect } from "react";
import Router from "next/router";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2 />
        <LoadingProvider>
          <LoadingWrapper>{children}</LoadingWrapper>
        </LoadingProvider>
      </body>
    </html>
  );
}

//
const LoadingWrapper = ({ children }) => {
  const { loading, startLoading, stopLoading } = useLoading();

  useEffect(() => {
    const handleStart = () => startLoading();
    const handleComplete = () => stopLoading();

    Router.events.on("routeChangeStart", handleStart);
    Router.events.on("routeChangeComplete", handleComplete);
    Router.events.on("routeChangeError", handleComplete);

    return () => {
      Router.events.off("routeChangeStart", handleStart);
      Router.events.off("routeChangeComplete", handleComplete);
      Router.events.off("routeChangeError", handleComplete);
    };
  }, [startLoading, stopLoading]);

  return (
    <>
      {loading && <LoadingScreen />}
      {children}
    </>
  );
};
